export const mockContext = {
  doctors: [
    {
      name: "Arslan",
      IsChecked: true,
    },
    {
      name: "Ahsan",
      IsChecked: false,
    },
    {
      name: "Doctor Name is Shahroz3",
      IsChecked: false,
    },
    {
      name: "Doctor Name is Shahroz4",
      IsChecked: false,
    },
    {
      name: "Doctor Name is Shahroz5",
      IsChecked: false,
    },
    {
      name: "Doctor Name is Shahroz6",
      IsChecked: false,
    },
  ],
  allForms: [
    // "cms1500",
    "labOrders",
    "referralForm",
    "admissionOrders",
    "impressionPlan",
    "initialAssesment",
    "faceToFace",
    // "teleMedicines",
    "medicationReconciliation",
    "intakeForm",
    "polst",
    "annualWellness",
    "assignmentInsurance",
    "recordsRelease",
    "checklistForTobacco",
    "fallRiskList",
  ],
  selectedForms: [
    // "cms1500",
    // "labOrders",
    "referralForm",
    "admissionOrders",
    "impressionPlan",
    "initialAssesment",
    "faceToFace",
    // "teleMedicines",
    "polst",
    "medicationReconciliation",
    "assignmentInsurance",
    "annualWellness",
    "checklistForTobacco",
    "fallRiskList",
    "recordsRelease",
    "intakeForm",
  ],
  labOrders: ["labOrders"],
  labReferences: [
    "CBC",
    "BMP",
    "CMP",
    "CMP1",
    "CMP2",
    "CMP3",
    "CMP4",
    "CMP5",
    "CMP6",
  ],
  selectedLabs: ["CBC", "BMP", "CMP", "CMP1"],
};
